//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA_Hackathon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Order
    {
        public Order()
        {
            this.Foods = new HashSet<Food>();
        }
    
        public int oid { get; set; }

        [Display(Name = "Student ID")]
        public string stid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Food> Foods { get; set; }
    }
}
